-- Extra fields for full agent-turn logging (MCP log_agent_response).

ALTER TABLE sessions
    ADD COLUMN IF NOT EXISTS project TEXT NOT NULL DEFAULT '';

ALTER TABLE session_prompts
    ADD COLUMN IF NOT EXISTS model TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS project TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS user_ip TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS token_usage TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS refined_prompt TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS is_accepted BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS log_date DATE,
    ADD COLUMN IF NOT EXISTS log_time TIME WITHOUT TIME ZONE;
